# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/openai_agents_sdk_repo',
                'doc_host': 'https://weiyunnaopenai.github.io',
                'git_url': 'https://github.com/weiyunnaopenai/openai_agents_sdk_repo',
                'lib_path': 'openai_agents_sdk_repo'},
  'syms': {'openai_agents_sdk_repo.core': {'openai_agents_sdk_repo.core.foo': ('core.html#foo', 'openai_agents_sdk_repo/core.py')}}}
